name: Main CI & CD workflow

on:
  push:
    branches: main
    paths:
     - package.json
     - .github/workflows/main.yml 
  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://registry.npmjs.org/
      - run: npm i -g npm@latest
      - run: npm clean-install
      - name: "Configure git"
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - run: npm run build
      - run: npm test --if-present
      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
      - name: "npm version"
        if: ${{ steps.publish.outputs.type }}
        run: npm version --allow-same-version $(node -p "require('./package.json').version")
      - name: "Push new version commit and tag"
        if: ${{ steps.publish.outputs.type }}
        run: (git push --tags && git push) || echo "Tag to the current version already exists"

